
gnc: utils.c image-io.c filter.c gnc.c pyramid.c pyramid-sor.c sor.c image_stats.c warp.c derivatives.c disconts.c warp-back.c
	cc -Wall utils.c image-io.c filter.c gnc.c pyramid.c pyramid-sor.c sor.c image_stats.c warp.c derivatives.c disconts.c warp-back.c -o gnc -lm

